import type { ThemeConfig } from 'antd'

// Tokens de docs/DESIGN.md §10 — aplicados al pie de la letra.
export const quantumTheme: ThemeConfig = {
  token: {
    colorPrimary: '#244481',
    colorPrimaryBg: '#f3f2ff',
    colorPrimaryBgHover: '#e4e7ff',
    colorPrimaryBorder: '#c4c6d1',
    colorPrimaryBorderHover: '#3e5c9a',
    colorPrimaryHover: '#3e5c9a',
    colorPrimaryActive: '#1b3466',
    colorPrimaryTextHover: '#3e5c9a',
    colorPrimaryText: '#244481',
    colorPrimaryTextActive: '#1b3466',

    colorSuccess: '#006a64',
    colorSuccessBg: '#92f3eb',
    colorSuccessBgHover: '#8ff0e8',
    colorSuccessBorder: '#75d7ce',
    colorSuccessHover: '#005f5a',
    colorSuccessActive: '#004e4a',
    colorSuccessText: '#006a64',
    colorSuccessTextHover: '#005f5a',
    colorSuccessTextActive: '#004e4a',

    colorWarning: '#d97706',
    colorWarningBg: '#fef3c7',

    colorError: '#ba1a1a',
    colorErrorBg: '#ffdad6',
    colorErrorBorder: '#f5a3a3',
    colorErrorHover: '#a01515',
    colorErrorActive: '#880f0f',
    colorErrorText: '#ba1a1a',

    colorInfo: '#244481',

    colorBgBase: '#fbf8ff',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgLayout: '#F4F7FE',
    colorBgSpotlight: '#ecedff',
    colorBgMask: 'rgba(13, 25, 62, 0.45)',

    colorText: '#0e193e',
    colorTextSecondary: '#444750',
    colorTextTertiary: '#747781',
    colorTextQuaternary: '#c4c6d1',
    colorTextDisabled: '#c4c6d1',
    colorTextPlaceholder: '#747781',
    colorTextHeading: '#0e193e',

    colorBorder: '#c4c6d1',
    colorBorderSecondary: '#e4e7ff',
    colorSplit: '#e4e7ff',

    colorFill: '#ecedff',
    colorFillSecondary: '#e4e7ff',
    colorFillTertiary: '#f3f2ff',
    colorFillQuaternary: '#fbf8ff',

    fontFamily: "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    fontFamilyCode: "'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    fontSize: 14,
    fontSizeSM: 12,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 32,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    lineHeight: 1.5714,
    lineHeightLG: 1.5,
    lineHeightSM: 1.3333,

    borderRadius: 4,
    borderRadiusSM: 4,
    borderRadiusLG: 8,
    borderRadiusXS: 2,

    padding: 20,
    paddingLG: 24,
    paddingXL: 32,
    paddingMD: 16,
    paddingSM: 12,
    paddingXS: 8,
    paddingXXS: 4,
    margin: 20,
    marginLG: 24,
    marginXL: 32,
    marginMD: 16,
    marginSM: 12,
    marginXS: 8,
    marginXXS: 4,

    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 44,
    controlHeightXS: 24,
    controlOutlineWidth: 2,
    controlItemBgHover: '#f3f2ff',
    controlItemBgActive: '#e4e7ff',
    controlItemBgActiveHover: '#dde1ff',
    controlItemBgActiveDisabled: '#ecedff',

    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
    boxShadowSecondary: '0 8px 30px rgba(0, 0, 0, 0.08)',
    boxShadowTertiary: '0 1px 4px rgba(0, 0, 0, 0.04)',

    motionDurationFast: '0.1s',
    motionDurationMid: '0.2s',
    motionDurationSlow: '0.3s',
    motionEaseInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
    motionEaseOut: 'cubic-bezier(0, 0, 0.2, 1)',

    wireframe: false,
  },
  components: {
    Button: {
      borderRadius: 9999,
      borderRadiusSM: 9999,
      borderRadiusLG: 9999,
      fontWeight: 600,
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
    },
    Tag: {
      borderRadius: 9999,
      fontSizeSM: 10,
    },
    Badge: {
      borderRadius: 9999,
    },
    Card: {
      borderRadius: 4,
      paddingLG: 20,
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.05)',
    },
    Table: {
      borderRadius: 4,
      headerBg: '#fbf8ff',
      headerColor: '#444750',
      rowHoverBg: '#f3f2ff',
      headerSortActiveBg: '#f3f2ff',
    },
    Input: {
      borderRadius: 4,
      activeBorderColor: '#244481',
      hoverBorderColor: '#3e5c9a',
      colorBgContainer: '#ffffff',
    },
    Select: {
      borderRadius: 4,
    },
    Modal: {
      borderRadius: 8,
      borderRadiusSM: 8,
    },
    Tabs: {
      inkBarColor: '#244481',
      itemActiveColor: '#244481',
      itemSelectedColor: '#244481',
      itemHoverColor: '#3e5c9a',
    },
    Menu: {
      itemBorderRadius: 4,
      itemSelectedBg: '#f3f2ff',
      itemSelectedColor: '#244481',
      itemHoverBg: '#ecedff',
      itemHoverColor: '#244481',
      activeBarBorderWidth: 2,
    },
    Typography: {
      titleMarginBottom: '0.5em',
      titleMarginTop: '1em',
      fontWeightStrong: 600,
    },
    Notification: {
      borderRadius: 8,
    },
    Message: {
      borderRadius: 8,
    },
    Avatar: {
      borderRadius: 9999,
      colorTextPlaceholder: '#afc6ff',
    },
  },
}
